### ISSUE TITLE
WQ function when no weights are provided

### ISSUE THREAD

**Issue by BasilSch** [gibonet/distrr#2]
The lines below do not produce the same results. 

distrr::wq(c(10,20,30,40,50,60),weights =rep(1,6),probs=c(0.25))
distrr::wq(c(10,20,30,40,50,60),probs=c(0.25))

Not even sure if this is really an issue that needs to be fixed. I might also be adressed with a warning message (use of quantile function if no weights are provided). Great package by the way. Many thanks!

**Comment by gibonet** [comment]
Sorry for the late response. Thank you for the observation, you are right. I changed a little bit distrr::wq(): in case the weights are missing, take equal weights (instead of using stats::quantile()).

Now (version 0.0.6.9000):
distrr::wq(c(10,20,30,40,50,60),weights =rep(1,6),probs=c(0.25))
distrr::wq(c(10,20,30,40,50,60),probs=c(0.25))

give the same result.
